### ISSUE TITLE
Add better violation handling

### ISSUE THREAD

**Issue by bcbwilla** [bcbwilla/FourierMC#8]
Need a good way to record / log user violations (i.e. when they fail a clicking signal test).  Possibly something that keeps track of violations over time and notifies server staff after a certain number of violations.  This should be general and play well with other standard server plugins.

**Comment by jedediah** [comment]
For our purposes, the ideal would be to fire a custom event (through the Bukkit event system) for each violation, and provide a way to disable any other record keeping or logging, since we already have our own reporting and logging systems.

This assumes that each violation is something that demands our attention. If false violations are frequent, then maybe another layer of analysis is required to detect patterns of violations that are interesting.

**Comment by bcbwilla** [comment]
Ok, that sounds good and that's the approach to take.  There definitely needs to be an analysis layer, so each test failure will fire off some custom violation event(s), and if that happens enough or in an interesting way some other event will be triggered.

**Comment by bcbwilla** [comment]
Violations are now in a reasonable state and I feel this issue can be closed.
